language: ruby
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - bundle exec rake test_app
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
script:
  - bundle exec rspec spec
notifications:
  email:
    - ryan@spreecommerce.com
  irc:
    use_notice: true
    skip_join: true
    channels:
      - "irc.freenode.org#spree"
rvm:
  - 1.9.3
  - 2.0.0
